name: Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./x86_64/buster
      run: docker build . --file Dockerfile --tag linux-buster-x86_64:$(date +%s)
