name: Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
#      working-directory: ./linux-qt5-x64-static
#      run: docker build . --file Dockerfile --tag linux-qt5-x64-static:$(date +%s)
      
    - uses: docker/login-action@v1.10.0
    - name: Login to docker hub
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
          images: atom63/test-docker 
          
    - uses: docker/build-push-action@v2.6.1
    - name: Build and push
      with:  
          file: ./linux-qt5-x64-static/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
    
      
