name: Docker Image CI

folder: "linux-qt5-x64-static"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file {{folder}}/Dockerfile --tag {{folder}}:$(date +%s)
