name: Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./linux-qt5-armv7a-static
      run: docker build . --file Dockerfile --tag linux-qt5-armv7a-static:$(date +%s)
